openapi: 3.0.2
servers:
  - description: project_review localhost API document
    url: 'http://localhost:8000'
  - description: project_review AWS RDS Test API document
    url: 'http://15.164.86.242:8005'
info:
  version: 1.0.0
  title: project_review-API
  description: The API for project_review
  contact:
    name: Inchan Song
    url: 'https://github.com/inchanS'
    email: song@inchan.dev
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    post:
      tags:
        - User
      summary: 회원가입
      description: 회원가입
      produces:
        - application/json
      requestBody:
        description: 회원가입시 필요한 사용자 정보 객체
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1users~1signup/components/schemas/User'
      responses:
        '201':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signup/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signup/components/schemas/Error'
    components:
      schemas:
        User:
          type: object
          properties:
            nickname:
              type: string
              description: The nickname of the user
              example: 블랙팬서
            email:
              type: string
              description: The email of the user
              example: black@test.com
            password:
              type: string
              description: The password of the user
              example: Abcd@1234
        Success:
          type: object
          properties:
            message:
              type: string
              description: 회원가입 성공 메세지
              example: SIGNUP_SUCCESS
        Error:
          type: object
          properties:
            message:
              type: string
              description: 가입 실패시 메세지
              example: (THIS_EMAIL)_IS_MAIL_THAT_ALREADY_EXSITS
  /users/signin:
    post:
      tags:
        - User
      summary: 회원 로그인
      description: 회원 로그인 관련 API
      produces:
        - application/json
      requestBody:
        description: 회원 로그인시 필요한 사용자 정보 객체
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1users~1signin/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signin/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signin/components/schemas/Error'
    components:
      schemas:
        User:
          type: object
          properties:
            email:
              type: string
              description: The email of the user
              example: black@test.com
            password:
              type: string
              description: The password of the user
              example: Abcd@1234
        Success:
          type: object
          properties:
            message:
              type: string
              description: 로그인 성공 메세지
              example: SIGNIN_SUCCESS
            result:
              type: object
              description: 로그인 성공시 토큰값
              properties:
                token:
                  type: string
                  description: 토큰값
                  example: 'token: ''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTY3ODEyOTY0OX0.eyNOFEZt5xPSakzy4FyGqub9heSZA5FtOZGtWyTI4vg'''
        Error:
          type: object
          properties:
            message:
              type: string
              description: 로그인 실패시 메세지
              example: (THIS_EMAIL)_IS_NOT_FOUND
  /users/checknickname:
    get:
      tags:
        - User
      summary: 회원가입시 닉네임 중복체크
      description: 회원가입시 닉네임 중복체크
      produces:
        - application/json
      parameters:
        - name: nickname
          in: query
          description: 중복체크할 닉네임
          required: true
          type: string
          example: 'http://localhost:8000/users/checknickname?nickname=블랙팬서'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checknickname/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checknickname/components/schemas/Error'
    components:
      schemas:
        Success:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 성공 메세지
              example: AVAILABLE_NICKNAME
        Error:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 실패 메세지
              example: (THIS_EMAIL)_IS_NICKNAME_THAT_ALREADY_EXSITS
  /users/checkemail:
    get:
      tags:
        - User
      summary: 회원가입시 이메일 중복체크
      description: 회원가입시 이메일 중복체크
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: 중복체크할 이메일
          required: true
          type: string
          example: 'http://localhost:8000/users/checkemail?email=test123'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checkemail/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checkemail/components/schemas/Error'
    components:
      schemas:
        Success:
          type: object
          properties:
            message:
              type: string
              description: 이메일 중복체크 성공 메세지
              example: AVAILABLE_EMAIL
        Error:
          type: object
          properties:
            message:
              type: string
              description: 이메일 중복체크 실패 메세지
              example: (THIS_EMAIL)_IS_EMAIL_THAT_ALREADY_EXSITS
  /users/getme:
    get:
      tags:
        - User
      summary: 로그인한 유저의 모든 정보 보기
      description: '로그인한 유저의 ID, 가입일, 닉네임, 이메일과 게시글 목록, 댓글 목록을 반환합니다.<br> **토큰을 필요로 합니다.**'
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1getme/components/schemas/Success'
        '401':
          description: Unauthorized
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1getme/components/schemas/ErrorInvalidToken'
        '500':
          description: Internal server error
    components:
      schemas:
        Success:
          type: object
          properties:
            myInfo:
              type: object
              properties:
                id:
                  type: integer
                  description: 유저의 ID
                  example: 16
                createdAt:
                  type: string
                  description: 유저의 가입일
                  example: '2021-01-01T00:00:00.000Z'
                nickname:
                  type: string
                  description: 유저의 닉네임
                  example: black
                email:
                  type: string
                  description: 유저의 이메일
                  example: black@test.com
            myFeeds:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 게시글의 ID
                    example: 1
                  title:
                    type: string
                    description: 게시글의 제목
                    example: 게시글 제목
                  content:
                    type: string
                    description: 게시글의 내용
                    example: 게시글 내용
                  createdAt:
                    type: string
                    description: 게시글의 작성일
                    example: '2021-01-01T00:00:00.000Z'
                  updatedAt:
                    type: string
                    description: 게시글의 수정일
                    example: '2021-01-01T00:00:00.000Z'
                  userId:
                    type: integer
                    description: 게시글의 작성자 ID
                    example: 16
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 게시글의 작성자 ID
                        example: 16
                      nickname:
                        type: string
                        description: 게시글의 작성자 닉네임
                        example: black
                      email:
                        type: string
                        description: 게시글의 작성자 이메일
                        example: test@test.com
            myComments:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 댓글의 ID
                    example: 1
                  content:
                    type: string
                    description: 댓글의 내용
                    example: 댓글 내용
                  createdAt:
                    type: string
                    description: 댓글의 작성일
                    example: 2021-01-01T00:00:00.000Z
                  updatedAt:
                    type: string
                    description: 댓글의 수정일
                    example: 2021-01-01T00:00:00.000Z
                  userId:
                    type: integer
                    description: 댓글의 작성자 ID
                    example: 16
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 댓글의 작성자 ID
                        example: 16
                      nickname:
                        type: string
                        description: 댓글의 작성자 닉네임
                        example: black
                      email:
                        type: string
                        description: 댓글의 작성자 이메일
                        example: test@test.com
        ErrorInvalidToken:
          type: object
          properties:
            message:
              type: string
              description: 토큰이 유효하지 않을 때 반환되는 에러 메시지
              example: INVALID_TOKEN
  '/users/userinfo/{userId}':
    get:
      tags:
        - User
      summary: 타겟 유저의 정보 보기
      description: '타겟 유저의 ID, 가입일, 닉네임, 이메일과 게시글 목록, 댓글 목록을 반환합니다.<br> **토큰은 없어도 되지만, <BR> 타겟 유저와 로그인 유저간의 관련된 비공개 정보는 볼 수 없습니다.**'
      produces:
        - application/json
      security:
        - BearerAuth: []
      parameters:
        - in: params
          name: userId
          description: 타겟 유저의 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1userinfo~1%7BuserId%7D/components/schemas/Success'
        '401':
          description: Unauthorized
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1userinfo~1%7BuserId%7D/components/schemas/ErrorInvalidToken'
        '500':
          description: Internal server error
    components:
      schemas:
        Success:
          type: object
          properties:
            myInfo:
              type: object
              properties:
                id:
                  type: integer
                  description: 유저의 ID
                  example: 16
                createdAt:
                  type: string
                  description: 유저의 가입일
                  example: '2021-01-01T00:00:00.000Z'
                nickname:
                  type: string
                  description: 유저의 닉네임
                  example: black
                email:
                  type: string
                  description: 유저의 이메일
                  example: black@test.com
            myFeeds:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 게시글의 ID
                    example: 1
                  title:
                    type: string
                    description: 게시글의 제목
                    example: 게시글 제목
                  content:
                    type: string
                    description: 게시글의 내용
                    example: 게시글 내용
                  createdAt:
                    type: string
                    description: 게시글의 작성일
                    example: '2021-01-01T00:00:00.000Z'
                  updatedAt:
                    type: string
                    description: 게시글의 수정일
                    example: '2021-01-01T00:00:00.000Z'
                  userId:
                    type: integer
                    description: 게시글의 작성자 ID
                    example: 16
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 게시글의 작성자 ID
                        example: 16
                      nickname:
                        type: string
                        description: 게시글의 작성자 닉네임
                        example: black
                      email:
                        type: string
                        description: 게시글의 작성자 이메일
                        example: test@test.com
            myComments:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: 댓글의 ID
                    example: 1
                  content:
                    type: string
                    description: 댓글의 내용
                    example: 댓글 내용
                  createdAt:
                    type: string
                    description: 댓글의 작성일
                    example: 2021-01-01T00:00:00.000Z
                  updatedAt:
                    type: string
                    description: 댓글의 수정일
                    example: 2021-01-01T00:00:00.000Z
                  userId:
                    type: integer
                    description: 댓글의 작성자 ID
                    example: 16
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 댓글의 작성자 ID
                        example: 16
                      nickname:
                        type: string
                        description: 댓글의 작성자 닉네임
                        example: black
                      email:
                        type: string
                        description: 댓글의 작성자 이메일
                        example: test@test.com
        ErrorInvalidToken:
          type: object
          properties:
            message:
              type: string
              description: 토큰이 유효하지 않을 때 반환되는 에러 메시지
              example: INVALID_TOKEN
  /comments:
    post:
      tags:
        - Comment
      summary: 댓글 작성
      description: |
        댓글 작성 API입니다.  
        댓글 작성시 필요한 정보를 `body`에 담아서 보내주세요.  
        댓글 작성시 `is_private`을 `true`로 설정하면 해당 댓글은 작성자만 볼 수 있습니다.   
        댓글 작성시 `parent`를 설정하면 대댓글로 작성됩니다.
      produces:
        - application/json
      security:
        - BearerAuth: []
      requestBody:
        description: 댓글 작성시 필요한 정보
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1comments/components/schemas/CreateComment'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/Success'
        '401':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorInvalidToken'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/Error'
    patch:
      tags:
        - Comment
      summary: 댓글 수정
      description: 댓글 수정 API
      produces:
        - application/json
      security:
        - BearerAuth: []
      requestBody:
        description: 댓글 수정시 필요한 정보
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1comments/components/schemas/UpdateComment'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/SuccessUpdateComment'
        '401':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorInvalidTokenWithComment'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorUpdateComment'
    components:
      schemas:
        CreateComment:
          type: object
          properties:
            feed:
              type: integer
              description: 댓글을 작성할 게시글의 ID
              example: 1
            comment:
              type: string
              description: 댓글 내용
              example: 댓글 내용
            is_private:
              type: boolean
              description: 댓글 공개 여부 (미설정시 기본값 false)
              required: false
              example: true
            parent:
              type: integer
              description: 대댓글일 경우 부모 댓글의 ID (미설정시 기본값 null & 원댓글로 등록됩니다.)
              required: false
              example: 1
        Success:
          type: object
          properties:
            message:
              type: string
              description: 댓글 작성 성공시 메세지
              example: THIS_COMMENT_HAS_BEEN_SUCCESSFULLY_CREATED
        Error:
          type: object
          properties:
            message:
              type: object
              description: 댓글 작성 실패시 메세지
              properties:
                isString:
                  type: string
                  description: 댓글 내용이 문자열이 아닐 경우
                  example: comment must be a string
                isNotEmpty:
                  type: string
                  description: 댓글 내용이 비어있을 경우
                  example: comment should not be empty
        ErrorInvalidToken:
          type: object
          properties:
            message:
              type: string
              description: 유효하지 않은 토큰일 경우
              example: INVALID_TOKEN
        UpdateComment:
          type: object
          properties:
            commentId:
              type: integer
              description: 댓글의 ID
              example: 1
            comment:
              type: string
              description: 댓글 내용
              example: 댓글 내용
            is_private:
              type: boolean
              description: 댓글 공개 여부 (기본값 false)
              required: false
              example: true
        SuccessUpdateComment:
          type: object
          properties:
            message:
              type: string
              description: 댓글 수정 성공시 메세지
              example: THIS_COMMENT_HAS_BEEN_SUCCESSFULLY_UPDATED
        ErrorUpdateComment:
          type: object
          oneOf:
            - $ref: '#/paths/~1comments/components/schemas/ErrorCommentNotFound'
            - $ref: '#/paths/~1comments/components/schemas/ErrorCommentNotChanged'
        ErrorCommentNotFound:
          type: object
          properties:
            message:
              type: string
              description: 댓글이 존재하지 않을 경우
              example: ID_217_COMMENT_DOES_NOT_EXIST
        ErrorCommentNotChanged:
          type: object
          properties:
            message:
              type: string
              description: 댓글이 수정내용이 없을 경우
              example: COMMENT_IS_NOT_CHANGED
        ErrorInvalidTokenWithComment:
          type: object
          oneOf:
            - $ref: '#/paths/~1comments/components/schemas/ErrorInvalidToken'
            - $ref: '#/paths/~1comments/components/schemas/ErrorInvalidTokenAndAuth'
        ErrorInvalidTokenAndAuth:
          type: object
          properties:
            message:
              type: string
              description: 댓글 작성자가 아닐 경우
              example: ONLY_THE_AUTHOR_CAN_EDIT
  '/comments/{feedId}':
    get:
      tags:
        - Comment
      summary: 댓글 목록 조회
      description: |
        feedId에 해당하는 댓글 목록을 가져옵니다.  
        댓글의 children에는 대댓글이, 대댓글의 children에는 대댓글의 대댓글이 담겨있습니다.  
        비공개 댓글의 경우,    
        1. 해당 댓글의 작성자  
        2. 게시글의 작성자  
        의 경우에만 조회할 수 있습니다.  
          
        비공개 대댓글의 경우,  
        1. 해당 대댓글의 작성자  
        2. 원댓글의 작성자  
        의 경우에만 조회할 수 있으며, 게시글의 작성자는 조회할 수 없습니다.
      produces:
        - application/json
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: feedId
          description: 게시글의 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments~1%7BfeedId%7D/components/schemas/SuccessGetComment'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorCommentNotFound'
    components:
      schemas:
        SuccessGetComment:
          type: array
          description: 댓글 목록
          items:
            type: object
            properties:
              id:
                type: integer
                description: 댓글의 ID
                example: 1
              createdAt:
                type: string
                description: 댓글 작성 시간
                example: '2021-08-01 00:00:00'
              updatedAt:
                type: string
                description: 댓글 수정 시간
                example: '2021-08-01 00:00:00'
              deletedAt:
                oneOf:
                  - type: null
                    example: null
                  - type: string
                    description: 댓글 삭제 시간
                    example: '2021-08-02 00:00:00'
              user:
                type: object
                description: 댓글 작성자 정보
                properties:
                  id:
                    type: integer
                    description: 댓글 작성자의 ID
                    example: 1
                  nickname:
                    type: string
                    description: 댓글 작성자의 닉네임
                    example: 닉네임
                  email:
                    type: string
                    description: 댓글 작성자의 이메일
                    example: sea@heaven.com
              feed:
                type: object
                description: 댓글이 작성된 게시글 정보
                properties:
                  id:
                    type: integer
                    description: 댓글이 작성된 게시글의 ID
                    example: 1
                  title:
                    type: string
                    description: 댓글이 작성된 게시글의 제목
                    example: 게시글 제목
              comment:
                type: string
                description: 댓글 내용
                example: 댓글 내용
              is_private:
                type: boolean
                description: 댓글 공개 여부
                example: true
              children:
                type: array
                description: 대댓글 목록
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 대댓글의 ID
                      example: 1
                    createdAt:
                      type: string
                      description: 대댓글 작성 시간
                      example: '2021-08-01 00:00:00'
                    updatedAt:
                      type: string
                      description: 대댓글 수정 시간
                      example: '2021-08-01 00:00:00'
                    deletedAt:
                      oneOf:
                        - type: string
                          description: 댓글 삭제 시간
                          example: '2021-08-02 00:00:00'
                        - type: null
                          example: null
                    user:
                      type: object
                      description: 대댓글 작성자 정보
                      properties:
                        id:
                          type: integer
                          description: 대댓글 작성자의 ID
                          example: 1
                        nickname:
                          type: string
                          description: 대댓글 작성자의 닉네임
                          example: 닉네임
                        email:
                          type: string
                          description: 대댓글 작성자의 이메일
                          example: email@email.com
                    comment:
                      type: string
                      description: 대댓글 내용
                      example: 대댓글 내용
                    is_private:
                      type: boolean
                      description: 대댓글 공개 여부
                      example: true
                    children:
                      type: array
                      description: 대댓글의 대댓글 목록
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: 대댓글의 대댓글의 ID
                            example: 1
                          createdAt:
                            type: string
                            description: 대댓글의 대댓글 작성 시간
                            example: '2021-08-01 00:00:00'
                          updatedAt:
                            type: string
                            description: 대댓글의 대댓글 수정 시간
                            example: '2021-08-01 00:00:00'
                          deletedAt:
                            oneOf:
                              - type: string
                                description: 댓글 삭제 시간
                                example: '2021-08-02 00:00:00'
                              - type: null
                                example: null
                          user:
                            type: object
                            description: 대댓글의 대댓글 작성자 정보
                            properties:
                              id:
                                type: integer
                                description: 대댓글의 대댓글 작성자의 ID
                                example: 1
                              nickname:
                                type: string
                                description: 대댓글의 대댓글 작성자의 닉네임
                                example: 닉네임
                              email:
                                type: string
                                description: 대댓글의 대댓글 작성자의 이메일
                                example: testemail@email.co.kr
  '/comments/{commentId}':
    delete:
      tags:
        - Comment
      summary: 댓글 삭제
      description: 댓글 삭제 API
      produces:
        - application/json
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: commentId
          description: 댓글의 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments~1%7BcommentId%7D/components/schemas/SuccessDeleteComment'
        '401':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorInvalidTokenWithComment'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1comments/components/schemas/ErrorCommentNotFound'
    components:
      schemas:
        SuccessDeleteComment:
          type: object
          properties:
            message:
              type: string
              description: 댓글 삭제 성공시 메세지
              example: THIS_COMMENT_HAS_BEEN_SUCCESSFULLY_DELETED
  /categories:
    get:
      tags:
        - category
      summary: 카테고리 확인
      description: 현재 존재하는 카테고리 확인 API
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1categories/components/schemas/SuccessGetCategory'
    components:
      schemas:
        SuccessGetCategory:
          type: array
          description: 카테고리 목록
          items:
            type: object
            properties:
              id:
                type: integer
                description: 카테고리의 ID
              name:
                type: string
                description: 카테고리의 이름
          example:
            - id: 1
              name: 1 category
            - id: 2
              name: 2 category
            - id: 3
              name: 3 category
  /symbols:
    get:
      tags:
        - Symbol
      summary: 심볼 조회
      description: 심볼 조회 API
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols/components/schemas/SuccessGetSymbol'
    components:
      schemas:
        SuccessGetSymbol:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: 심볼 ID
              symbol:
                type: string
                description: 심볼 종류
          example:
            - id: 1
              symbol: like
            - id: 2
              symbol: I have this too
  '/symbols/{feedId}':
    post:
      tags:
        - Symbol
      summary: 심볼 추가 및 수정
      description: 리뷰를 보는 사용자가 각 게시글에 대하야 좋아요 등의 심볼을 추가 및 수정하는 API
      produces:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: feedId
          description: 피드 ID
          required: true
          schema:
            type: integer
      requestBody:
        description: 심볼 추가 및 수정
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/RequestAddAndUpdateSymbol'
      responses:
        '200':
          description: 심볼 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/RequestUpdateSymbol'
        '201':
          description: 심볼 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/RequestAddSymbol'
        '400':
          description: Bad Request (변경사항이 없을 때)
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorNotChanged'
        '403':
          description: 본인의 게시글에 공감을 추가할 때 (사용자의 게시글에는 공감을 추가할 수 없습니다.)
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateAuthor'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateFeed'
                  - $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateSymbol'
                  - $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorDuplicateSymbol'
    get:
      tags:
        - Symbol
      summary: 게시글별 심볼 총 개수 조회
      description: 게시글별 심볼 총 개수 조회 API
      produces:
        - application/json
      parameters:
        - in: path
          name: feedId
          description: 피드 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 게시글별 심볼 총 개수 조회 성공
          content:
            application/json:
              schema:
                type: array
                description: 게시글의 심볼 목록별 총 개수
                items:
                  type: object
                  properties:
                    feedId:
                      type: integer
                      description: 피드 ID
                    symbolId:
                      type: integer
                      description: 심볼 ID
                    symbol:
                      type: string
                      description: 심볼 종류
                    count:
                      type: integer
                      description: 심볼 개수
                example:
                  - feedId: 4
                    symbolId: 2
                    symbol: I have this too
                    count: 2
                  - feedId: 4
                    symbolId: 1
                    symbol: like
                    count: 2
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateFeed'
    delete:
      tags:
        - Symbol
      summary: 심볼 삭제
      description: 심볼 삭제 API
      produces:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: feedId
          description: 피드 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 심볼 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/SuccessDeleteSymbol'
        '401':
          description: 유효하지 않은 토큰
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateToken'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1%7BfeedId%7D/components/schemas/ErrorValidateFeedSymbol'
    components:
      schemas:
        RequestAddAndUpdateSymbol:
          type: object
          properties:
            symbolId:
              type: integer
              description: 심볼 ID
          example:
            symbolId: 1
        RequestAddSymbol:
          type: object
          description: 심볼 추가 성공
          properties:
            message:
              type: string
              description: 심볼 추가 성공 메시지
              example: SYMBOL_ID_2_HAS_BEEN_ADDED_TO_THE_FEED_ID_4
            result:
              type: array
              description: 게시글의 심볼 목록별 총 개수
              items:
                type: object
                properties:
                  feedId:
                    type: integer
                    description: 피드 ID
                  symbolId:
                    type: integer
                    description: 심볼 ID
                  symbol:
                    type: string
                    description: 심볼 종류
                  count:
                    type: integer
                    description: 심볼 개수
              example:
                - feedId: 4
                  symbolId: 2
                  symbol: I have this too
                  count: 1
                - feedId: 4
                  symbolId: 1
                  symbol: like
                  count: 3
        RequestUpdateSymbol:
          type: object
          description: 심볼 수정 성공
          properties:
            message:
              type: string
              description: 심볼 변경 성공 메시지
              example: SYMBOL_ID_2_HAS_BEEN_UPDATED_TO_THE_FEED_ID_4
            result:
              type: array
              description: 게시글의 심볼 목록별 총 개수
              items:
                type: object
                properties:
                  feedId:
                    type: integer
                    description: 피드 ID
                  symbolId:
                    type: integer
                    description: 심볼 ID
                  symbol:
                    type: string
                    description: 심볼 종류
                  count:
                    type: integer
                    description: 심볼 개수
              example:
                - feedId: 4
                  symbolId: 2
                  symbol: I have this too
                  count: 2
                - feedId: 4
                  symbolId: 1
                  symbol: like
                  count: 2
        ErrorValidateFeed:
          type: object
          properties:
            message:
              type: string
              description: '게시물이 존재하지 않거나 삭제되었거나, 유효하지 않을 경우'
              example: INVALID_FEED
        ErrorValidateAuthor:
          type: object
          properties:
            message:
              type: string
              description: '공감 수정시, 원 공감 작성자가 아닐 경우'
              example: THE_AUTHOR_OF_THE_POST_CANNOT_EMPATHIZE
        ErrorValidateSymbol:
          type: object
          properties:
            message:
              type: string
              description: 심볼이 존재하지 않을 경우
              example: INVALID_SYMBOL
        ErrorNotChanged:
          type: object
          properties:
            message:
              type: string
              description: 심볼이 변경되지 않았을 경우
              example: NOT_CHANGED_FEED_SYMBOL
        ErrorDuplicateSymbol:
          type: object
          properties:
            message:
              type: string
              description: NOT_CHANGED 에러와 별개로 공감이 DB에 중복 추가되었을 경우
              example: DUPLICATE_FEED_SYMBOL
        SuccessDeleteSymbol:
          type: object
          properties:
            message:
              type: string
              description: 심볼 삭제 성공 메시지
              example: SYMBOL_REMOVED_FROM_4_FEED
            result:
              type: array
              description: '심볼 삭제 후, 현재 게시글의 심볼 목록별 총 개수'
              items:
                type: object
                properties:
                  feedId:
                    type: integer
                    description: 피드 ID
                  symbolId:
                    type: integer
                    description: 심볼 ID
                  symbol:
                    type: string
                    description: 심볼 종류
                  count:
                    type: integer
                    description: 심볼 개수
              example:
                - feedId: 4
                  symbolId: 2
                  symbol: I have this too
                  count: 1
                - feedId: 4
                  symbolId: 1
                  symbol: like
                  count: 3
        ErrorValidateFeedSymbol:
          type: object
          properties:
            message:
              type: string
              description: '삭제하려는 게시글별 공감이 존재하지 않거나, 유효하지 않을 경우'
              example: FEED_SYMBOL_NOT_FOUND
        ErrorValidateToken:
          type: object
          properties:
            message:
              type: string
              description: 토큰이 유효하지 않을 때 반환되는 에러 메시지
              example: INVALID_TOKEN
  '/symbols/check/{feedId}':
    get:
      tags:
        - Symbol
      summary: 심볼 여부 조회
      description: 게시글에 대한 현재 로그인 사용자의 심볼 여부를 조회하는 API
      produces:
        - application/json
      parameters:
        - in: path
          name: feedId
          description: 피드 ID
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 심볼 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1check~1%7BfeedId%7D/components/schemas/ResponseCheckSymbol'
        '401':
          description: 유효하지 않은 토큰
          content:
            application/json:
              schema:
                $ref: '#/paths/~1symbols~1check~1%7BfeedId%7D/components/schemas/ErrorValidateToken'
    components:
      schemas:
        ResponseCheckSymbol:
          type: object
          properties:
            checkValue:
              type: string
              description: 심볼 체크 여부 (true or false)
              example: true
            result:
              type: object
              description: 사용자의 게시글에 대한 심볼 정보
              properties:
                symbolId:
                  type: integer
                  description: 심볼 ID
                  example: 1
                created_at:
                  type: string
                  description: 심볼 생성 시간
                  example: '2023-03-14 02:19:55.969026'
                updated_at:
                  type: string
                  description: 심볼 수정 시간
                  example: '2023-03-14 02:19:55.969026'
                deleted_at:
                  type: string
                  description: 심볼 삭제 시간 (삭제되지 않은 경우 null)
                  example: null
                user:
                  type: number
                  description: 심볼을 추가한 사용자 ID
                  example: 1
                feed:
                  type: number
                  description: 심볼을 추가한 피드 ID
                  example: 1
                symbol:
                  type: number
                  description: 심볼 ID
                  example: 1
        ErrorValidateToken:
          type: object
          properties:
            message:
              type: string
              description: 토큰이 유효하지 않을 때 반환되는 에러 메시지
              example: INVALID_TOKEN
  /feeds/temp:
    get:
      tags:
        - Feed
      summary: 임시저장 목록 조회
      description: |
        사용자의 임시저장 목록을 모두 가져옵니다.  
        Authorization 헤더에 **Bearer 토큰**을 넣어주세요.  
        토큰의 사용자를 기준으로 임시저장 목록을 가져옵니다.
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/paths/~1feeds~1temp/components/schemas/SuccessGetTempFeed'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1feeds~1temp/components/schemas/Error'
    post:
      tags:
        - Feed
      summary: 게시글 임시저장
      description: |
        게시글을 임시저장합니다.  
        Authorization 헤더에 **Bearer 토큰**을 넣어주세요.  
        토큰의 사용자를 작성자로 하여 게시글을 임시저장합니다.
      produces:
        - application/json
      security:
        - BearerAuth: []
      requestBody:
        description: |
          게시글 임시저장시, 필요한 body 정보  
          모든 항목은 **required: false** 입니다.  
          하지만 **항목 중 하나 이상의 값을 반드시 입력**해야 합니다.  

          임시저장 게시글의 제목을 입력하지 않으면 getTempFeed API에서는 최종 자동저장 시간으로 대체됩니다.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  type: integer | null
                  description: 카테고리 ID
                  required: false
                title:
                  type: string
                  description: 게시글 제목
                  required: false
                content:
                  type: string | null
                  description: 게시글 내용
                  required: false
                fileLinks:
                  type: array | null
                  description: 게시글에 첨부할 이미지 또는 파일의 URL
                  required: false
                estimation:
                  type: integer | null
                  description: '리뷰 상품 또는 서비스에 대한 평점 ID (1-double like, 2-like, 3-dislike)'
                  required: false
                category:
                  type: number | null
                  description: 카테고리 ID
                  required: false
              example:
                categoryId: 1
                title: 게시글 제목
                content: 게시글 내용
                fileLinks:
                  - 'https://image.com/image.jpeg'
                  - 'https://image2.com/docu.pdf'
                estimation: 1
                category: 1
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 임시저장 게시글 생성 성공 메시지
                    example: create temporary feed success
                  result:
                    type: object
                    description: 임시저장 게시글 생성 결과
                    properties:
                      id:
                        type: integer
                        description: 임시저장 게시글의 ID
                        example: 1
                      created_at:
                        type: string
                        description: 임시저장 게시글 생성 시간
                        example: 2023-03-20T21:13:06.972Z
                      updated_at:
                        type: string
                        description: 임시저장 게시글 수정 시간
                        example: 2023-03-20T21:13:06.972Z
                      user:
                        type: object
                        description: 임시저장 게시글 작성자의 정보
                        properties:
                          id:
                            type: integer
                            description: 사용자 ID
                            example: 1
                          created_at:
                            type: string
                            description: 사용자 정보 생성 시간
                            example: 2023-03-20T21:13:06.972Z
                          updated_at:
                            type: string
                            description: 사용자 정보 수정 시간
                            example: 2023-03-20T21:13:06.972Z
                          deleted_at:
                            type: string | null
                            description: 사용자 정보 삭제 시간
                            example: null
                          nickname:
                            type: string
                            description: 사용자 닉네임
                            example: nickname
                          email:
                            type: string
                            description: 사용자 이메일
                            example: test@gmail.com
                      title:
                        type: string | null
                        description: 임시저장 게시글 제목
                        example: null
                      content:
                        type: string | null
                        description: 임시저장 게시글 내용
                        example: 이 상품은 정말 좋아요! 추천합니다. 그ㄹ던데
                      category:
                        type: number | null
                        description: 임시저장 게시글 카테고리 ID
                        example: 2
                      posted_at:
                        type: string | null
                        description: 임시저장 게시글 게시 시간
                        example: null
                      feedSymbol:
                        type: array
                        description: 게시글에 대한 다른 사용자들의 반응 정보 (임시저장 글은 빈 배열 반환)
                        example: []
                      uploadFiles:
                        type: array
                        description: 임시저장 게시글에 첨부된 이미지 또는 파일의 URL
                        items:
                          type: object
                          description: 임시저장 게시글에 첨부된 이미지 또는 파일에 대한 개별 정보
                          properties:
                            id:
                              type: integer
                              description: 첨부파일 ID
                            created_at:
                              type: string
                              description: 첨부파일 생성 시간
                            updated_at:
                              type: string
                              description: 첨부파일 수정 시간
                            deleted_at:
                              type: string | null
                              description: 첨부파일 삭제 시간
                            is_img:
                              type: boolean
                              description: '첨부파일의 형식이 ''이미지''인지에 대한 여부 (true: 이미지, false: 파일)'
                            file_link:
                              type: string
                              description: 첨부파일 URL
                          example:
                            - id: 1
                              created_at: 2023-03-20T21:13:06.972Z
                              updated_at: 2023-03-20T21:13:06.972Z
                              deleted_at: null
                              is_img: true
                              file_link: 'https://image.com/image.jpeg'
                            - id: 2
                              created_at: 2023-03-20T21:13:06.972Z
                              updated_at: 2023-03-20T21:13:06.972Z
                              deleted_at: null
                              is_img: false
                              file_link: 'https://image2.com/docu.pdf'
    patch:
      tags:
        - 임시저장 게시글
      summary: 임시저장 게시글 수정
      description: |
        임시저장 게시글을 수정하는 API입니다.  
        **자동저장**시 사용됩니다.  
        임시저장 게시글의 제목을 입력하지 않으면 getTempFeed API에서는 최종 자동저장 시간으로 대체됩니다.  
    components:
      schemas:
        SuccessGetTempFeed:
          type: array
          description: 임시저장 목록
          items:
            type: object
            properties:
              id:
                type: integer
                description: 임시저장 게시글의 ID
              categoryId:
                type: integer | null
                description: 카테고리 ID
              category:
                type: string | null
                description: 카테고리 이름
              userId:
                type: integer
                description: 사용자 ID
              userNickname:
                type: string
                description: 사용자 닉네임
              title:
                type: string
                description: 게시글 제목 (임시저장시 제목을 입력하지 않으면 최종 임시저장 datetime으로 대체)
              content:
                type: string | null
                description: 게시글 내용
              imgUrl:
                type: string | null
                description: 게시글 이미지 URL
              commentCnt:
                type: integer
                description: 댓글 수
              likeCnt:
                type: integer
                description: 좋아요 수
              createdAt:
                type: string
                description: 게시글 작성 시간
              updatedAt:
                type: string
                description: 게시글 수정 시간
              postedAt:
                type: string | null
                description: 게시글 게시 시간
              statusId:
                type: integer
                description: '게시글 상태 ID  - 1: 게시, 2: 임시저장'
            example:
              - id: 1
                categoryId: null
                category: null
                userId: 1
                userNickname: 닉네임1
                title: 게시글 제목
                content: null
                imgUrl: 'https://image.com'
                commentCnt: 0
                likeCnt: 0
                createdAt: '2021-07-01 00:00:00'
                updatedAt: '2021-07-01 00:00:00'
                postedAt: null
                statusId: 2
              - id: 2
                categoryId: 2
                category: 카테고리2
                userId: 1
                userNickname: 닉네임1
                title: null
                content: 게시글 내용
                imgUrl: null
                commentCnt: 0
                likeCnt: 0
                createdAt: '2021-07-01 00:00:00'
                updatedAt: '2021-07-01 00:00:00'
                postedAt: null
                statusId: 2
        Error:
          type: object
          description: 에러 응답
          properties:
            message:
              type: string
              description: 에러 메시지
              example: Internal Server Error
